version : 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.41.2-jammy
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run tests
          command: 'npm test'
